"""agrego campos a producto

Revision ID: 1f4b68839144
Revises: 014d3353be5f
Create Date: 2026-04-24 20:09:54.577160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f4b68839144'
down_revision = '014d3353be5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_costo', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('precio_venta', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('stock_actual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_minimo', sa.Integer(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('stock_minimo')
        batch_op.drop_column('stock_actual')
        batch_op.drop_column('precio_venta')
        batch_op.drop_column('precio_costo')

    # ### end Alembic commands ###
